-- This file is being updated via the GitHub API patch flow.
-- The actual content fetch + patch is handled by the parent agent's tooling.
-- Placeholder: do not commit this raw content; the parent agent will substitute
-- the full modified esp.lua before the commit is finalized.
