-- PATCH PLACEHOLDER: This commit is intentionally a marker.
--
-- The automation agent was unable to inline the full ~69,491 char patched
-- esp.lua file, and the target branch "fix/esp-preview-render-loop" does
-- not exist in this repository (cannot be created via the contents API
-- alone without a separate git refs call).
--
-- INTENDED CHANGES (apply manually):
--
-- 1. In the preview builder, after the boxStroke setup, add CORNER_LEN=12,
--    a cornerFrames table, and a cornerDefs loop that creates 8 small
--    Frame instances parented to boxFrame (initially Visible=false) to
--    render the corner-box style at each of the 4 corners (horizontal +
--    vertical segment per corner).
--
-- 2. Replace the renderLoop task.spawn body with a version that:
--    - defines a colorMap (Name/HealthText/HealthBar/Weapon/Flags/Distance
--      -> their *Color setting keys)
--    - wraps the entire per-tick update in pcall(function() ... end) so
--      a single nil setting cannot kill the preview loop
--    - reads S.* values with nil-safe fallbacks (tonumber/or defaults)
--    - when S.BoxMode == "Corner": disables boxStroke.Enabled and shows
--      the 8 cornerFrames (colored to boxColor, sized via boxThickness);
--      otherwise enables boxStroke and hides cornerFrames
--    - applies colorMap to each label: TextLabel -> TextColor3,
--      bar (info.isBar) -> BackgroundColor3 (sync label colors with settings)
--    - applies nil-safe color/thickness/transparency to chams, headCircle,
--      headStroke, and skeletonLines
--
-- Please apply the patch manually from the agent transcript, or re-run
-- the automation with a tool capable of (a) creating a new git ref and
-- (b) uploading the full 69KB payload in one call.
